In [1]:
# Imports
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt

In [2]:
df_0 = pd.read_csv('EMG Data/0.csv')
df_1 = pd.read_csv('EMG Data/1.csv')
df_2 = pd.read_csv('EMG Data/2.csv')
df_3 = pd.read_csv('EMG Data/3.csv')

In [3]:
def data_reformat(df, gesture):
    # Drop gesture column
    df.drop(df.columns[len(df.columns)-1], axis=1, inplace=True)
    
    # Reshape each 1x64 row into an 8x8
    bigdata = pd.DataFrame()
    for row in df.iloc[:,].values:
        reshape = np.reshape(row, (8,8))
        temp_df = pd.DataFrame(reshape)
        bigdata = bigdata.append(temp_df,ignore_index=True)
        
    # Add back gesture column
    bigdata['Gesture'] = gesture
    
    # Data windowing w/ Window Size = 200ms & Overlap = 50ms (each row = 5ms, 200/5 = 40 rows)
    start_pos = 0
    end_pos = 40
    num_windows = 0
    final = pd.DataFrame()
    for row in bigdata.iloc[:,].values:
        # Print start/end window position for checking
        # print('(',start_pos,',',end_pos,']')
        window = bigdata.iloc[start_pos:end_pos,:]
        final = final.append(window,ignore_index=True)
        start_pos += 30
        end_pos += 30
        num_windows += 1
        if end_pos > bigdata.shape[0]:
            break
    print('Total number of windows: ', num_windows)
    return final

In [4]:
gesture_0 = data_reformat(df_0, 0)
gesture_0.to_csv('gesture_0.csv', index = False) 
gesture_0

Total number of windows:  775

          0     1     2     3     4     5      6     7  Gesture
0     -47.0  -6.0  -5.0  -7.0  13.0  -1.0   35.0 -10.0        0
1      10.0  -4.0   0.0   7.0 -31.0 -33.0  -48.0 -52.0        0
2      34.0  10.0   5.0  -9.0  23.0  63.0   76.0  49.0        0
3     -27.0  -7.0  -7.0  -3.0   0.0   4.0 -111.0  -2.0        0
4      -7.0   7.0  11.0  11.0   2.0   2.0   76.0   3.0        0
...     ...   ...   ...   ...   ...   ...    ...   ...      ...
30995  -7.0   4.0   4.0   2.0   1.0   4.0  -55.0  -4.0        0
30996  -2.0  -2.0  -2.0   1.0  -3.0 -17.0  -33.0 -13.0        0
30997   3.0   2.0   2.0   6.0   0.0 -13.0   -7.0   5.0        0
30998  -2.0  -4.0   1.0   6.0  -5.0  -2.0  -33.0  -5.0        0
30999  -2.0   2.0   0.0  -3.0  17.0  12.0   56.0   0.0        0

[31000 rows x 9 columns]

In [5]:
gesture_1 = data_reformat(df_1, 1)
gesture_1.to_csv('gesture_1.csv', index = False) 
gesture_1

Total number of windows:  773

          0    1    2    3     4     5    6     7  Gesture
0      -6.0 -2.0 -5.0 -2.0  27.0  42.0  3.0   5.0        1
1      11.0  1.0 -1.0 -1.0  -3.0   2.0 -1.0 -10.0        1
2     -35.0 -2.0  4.0  6.0 -16.0 -12.0 -1.0   0.0        1
3      47.0  8.0  4.0 -2.0 -20.0 -23.0  0.0   8.0        1
4      -8.0 -1.0 -2.0 -2.0  12.0  -1.0 -2.0  -6.0        1
...     ...  ...  ...  ...   ...   ...  ...   ...      ...
30915 -24.0 -7.0 -2.0 -4.0 -12.0  -5.0 -5.0  -1.0        1
30916 -17.0 -5.0 -3.0 -4.0  10.0 -10.0  0.0   2.0        1
30917  -1.0 -3.0 -2.0 -2.0 -17.0   6.0  4.0   1.0        1
30918 -14.0 -2.0  0.0 -6.0  -3.0  18.0 -1.0  -7.0        1
30919  10.0  0.0 -3.0  2.0  34.0  42.0  3.0   6.0        1

[30920 rows x 9 columns]

In [6]:
gesture_2 = data_reformat(df_2, 2)
gesture_2.to_csv('gesture_2.csv', index = False) 
gesture_2

Total number of windows:  784

          0     1     2     3     4     5     6     7  Gesture
0      -1.0  12.0  20.0   7.0  20.0 -73.0  -4.0  -2.0        2
1       4.0   5.0 -14.0  -4.0 -16.0 -12.0  -6.0   0.0        2
2      -2.0 -30.0  13.0  17.0  20.0  82.0   0.0   6.0        2
3       7.0 -10.0  -4.0 -11.0 -41.0 -75.0 -20.0 -13.0        2
4     -13.0  -2.0  -2.0  11.0  44.0  77.0  37.0   1.0        2
...     ...   ...   ...   ...   ...   ...   ...   ...      ...
31355   1.0  22.0   1.0  -5.0  14.0  -6.0   1.0   5.0        2
31356  -1.0   7.0   0.0  -1.0   4.0  13.0   0.0  -7.0        2
31357  19.0  38.0   7.0   3.0   6.0  -5.0  -2.0   7.0        2
31358  -8.0 -81.0  -6.0  -2.0 -14.0 -36.0  -3.0  -3.0        2
31359  -3.0   2.0   1.0  -1.0  13.0   7.0  -4.0  -3.0        2

[31360 rows x 9 columns]

In [7]:
gesture_3 = data_reformat(df_3, 3)
gesture_3.to_csv('gesture_3.csv', index = False) 
gesture_3

Total number of windows:  778

          0    1    2    3     4     5    6     7  Gesture
0      -7.0  0.0  1.0  0.0 -13.0 -18.0  0.0  -9.0        3
1      -6.0 -2.0 -3.0 -4.0   4.0 -12.0 -9.0  -4.0        3
2      16.0  0.0  1.0 -2.0  -4.0 -34.0  0.0  -3.0        3
3      -5.0 -4.0 -3.0 -1.0 -12.0  -4.0 -8.0 -16.0        3
4      -4.0  1.0  1.0  1.0   2.0 -16.0  8.0   7.0        3
...     ...  ...  ...  ...   ...   ...  ...   ...      ...
31115 -10.0  1.0  4.0  0.0  -3.0  33.0 -2.0  -1.0        3
31116  -1.0  2.0 -3.0  0.0 -38.0 -25.0  0.0   3.0        3
31117   2.0 -1.0  0.0 -3.0  14.0   0.0 -1.0  -3.0        3
31118  -3.0 -4.0 -3.0 -6.0  -2.0  13.0 -5.0 -19.0        3
31119  -6.0 -5.0 -4.0  1.0  41.0 -10.0 -4.0  -9.0        3

[31120 rows x 9 columns]